### ISSUE TITLE
Splash 구성

### ISSUE THREAD

**Issue by daehwan2yo** [Team-Smeme/Smeme-android#14]
## 요약
- onBoarding 구현
 
## TODO
- Lottie 를 적용해 Splash 를 구성한다.
- 로컬 스토리지를 바탕으로 자동 로그인 여부를 판단해야한다.

### Check List
- [x] Lottie 적용 
- [x] 로그인 정보를 저장할 storage 자료 조사
- [x] BinderActivity 로 이동하도록 임시 구현
  - [x] 이후 storage 정보에 따라 Login 혹은 Home 분기 이동

## 참고
- https://developer.android.com/training/data-storage/shared-preferences?hl=en
