### ISSUE TITLE
MyDiaryFragment 구현

### ISSUE THREAD

**Issue by haeti-dev** [Team-Smeme/Smeme-android#19]
## 요약
기본 HomeActivity 생성 및 MyDiaryHomeFragement 구현

## TODO
홈 화면 확장성 고려

### Check List
- [x] toolbar 만들기
- [x] Recycler view 만들기
- [x] 재활용 될 아이템 만들기
- [x] adatper 생성
- [x] floatingActionButton 만들기
- [x] 바텀 네비게이션바 만들기
- [x] changeFragment 만들어 놓기
- [x] fab plus 눌렀을 때 배경 흐리게
- [x] fab 바깥 눌렀을 때 취소 처리 되게 하기
- [x] 글자 600자 자르기
- [x] 작성한 일기 없을 때 recycler view 안보이게
- [x] 서버 연결
- [x] 일기 삭제하기
- [ ] 일기 수정하기
- [x] fab와 다음 view들 연결

## 참고
changeFrament에 TODO로 놔두었으니 본인 fragment 연결하면 됨
