### ISSUE TITLE
한국어로 일기 작성 UI 구현

### ISSUE THREAD

**Issue by haeti-dev** [Team-Smeme/Smeme-android#26]
## 요약
한국어로 일기 작성 UI 구현
## TODO
UI 디테일까지 전부 구현
### Check List
- [x] 상단바 만들기
- [x] 키보드 커서 포커싱 
- [x] tips 색 바꾸기
- [ ] edit text 밑줄 제거
- [x] FAB이랑 연결
- [x] snack bar 만들기
- [x] 하단 설정 창 만들기
- [x] 렌덤 주제 연결
- [x] 렌덤 주제 UI 설정

**Comment by haeti-dev** [comment]
렌덤주제 연결에 관해 의견 공유하고 싶습니다
