### ISSUE TITLE
둘러보기 상세 스크랩 기능 구현

### ISSUE THREAD

**Issue by wateralsie** [Team-Smeme/Smeme-android#33]
## 요약
스크랩 기능 구현

## TODO
* 일단 기본 메뉴 최대한 활용
* text selection 메뉴 커스텀
* '스크랩' 항목 선택 -> 드래그된 텍스트값 저장 

### Check List
- [x] 복사, 붙여넣기 등 기본 항목 없애기
- [x] 스크랩 항목 추가
- [x] 스크랩 항목이 타어플 항목 (구글, 파파고 등) 의 앞쪽으로 가도록 하기  -> 타어플 항목 없애기
- [ ] 메뉴 스타일 적용
- [x] 스크랩 항목 누르면 선택된 텍스트가 저장되도록

## 참고
https://developer.android.com/develop/ui/views/components/menus#CABforViews
https://stackoverflow.com/questions/43689020/how-to-display-popup-instead-of-cab-when-textview-is-selected
