### ISSUE TITLE
QA checklist 반영

### ISSUE THREAD

**Issue by haeti-dev** [Team-Smeme/Smeme-android#43]
## 요약
QA checklist 반영

### TO-BE
모두 가능하게 기능 개선

- [x] 작성 완료 버튼 클릭 시 상세보기로 넘어가게 조정
- [x] Step2에서 영어 키보드가 나오게 조정
- [ ] 둘러보기 새로고침 (스와이프 X 상세보기에서 뒤로가기 눌렀을 때 데이터 갱신)
- [ ] 스크랩 이력 최신순으로 조정
- [x] 보관함 삭제하기 팝업 생성
